# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0' 
 
target:'PullToRefresh' do 
    #约束
    pod 'SnapKit'
   
end


